# ProGuard Configuration for TRCore

-dontshrink
-dontoptimize
-dontnote **
-dontwarn **
-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod

# Eklentinin ana sinifini koru ki server tarafindan baslatilabilsin
-keep public class com.trcore.TRCore {
    public void onEnable();
    public void onDisable();
    public void onLoad();
    public *;
}

# Tum Bukkit event listener fonksiyonlarini koru (Eventler patlamasin)
-keepclassmembers class * implements org.bukkit.event.Listener {
    @org.bukkit.event.EventHandler public *;
}

# PlaceholderAPI destek siniflarini koru (Baglanti kopmasin)
-keep public class com.trcore.elo.EloPlaceholderExpansion {
    public *;
}

# FoliaLib kutuphanesini (Gomme) kirilmaya karsi koru
-keep class org.maske.trcore.lib.folialib.** { *; }
-keep class com.tcoded.folialib.** { *; }

# Eklenti iskeletini a.b.c seklinde sifrele
-repackageclasses org.maske.trcore.obf
