name: mCore
version: 4.8
main: com.mcore.mCore
api-version: 1.21
authors: [ maskecik ]
description: en iyi sunucuya en iyi core
website: https://github.com/themaskee
depend: [PlaceholderAPI]
softdepend: [Vault]

commands:
  gmc:
    description: Yaratici mod.
    permission: mcore.gamemode
  gms:
    description: Hayatta kalma modu.
    permission: mcore.gamemode
  gmsp:
    description: Izleyici modu.
    permission: mcore.gamemode
  fly:
    description: Ucus modu.
    permission: mcore.fly
  walkspeed:
    description: Yurume hizi.
    permission: mcore.speed
  flyspeed:
    description: Ucus hizi.
    permission: mcore.speed
  lightning:
    description: Simsek.
    permission: mcore.lightning
  sudo:
    description: Sudo komutu.
    permission: mcore.sudo
  playerinfo:
    description: Oyuncu bilgisi.
    permission: mcore.playerinfo
  alts:
    description: Yan hesaplar.
    permission: mcore.alts
  clearchat:
    description: Sohbeti temizler.
    permission: mcore.clearchat
  mcore:
    description: Reload komutu.
    permission: mcore.admin
  tpa:
    description: TPA ana komutu.
  tpahere:
    description: TPA Here istegi.
  tpacancel:
    description: Istegi iptal et.
  tpaevent:
    description: TPA Etkinligi.
  rtpqueue:
    description: 1v1 sirasi.
  rtpduel:
    description: Duello istegi.
  back:
    description: Onceki konuma doner.
    permission: mcore.back